SRE-2535: add license as expected by OpenSSF Scorecard
daos-stack/fio pull request #11
Opened 2024-10-02 15:29 UTC by grom72

Inherit BSD-2-Clause-Patent License
from the main - daos-stack/daos project.

2024-10-02 18:16 UTC, osalyk approved these changes

2024-10-04 07:49 UTC, janekmi requested changes

2024-10-04 07:49 UTC, janekmi commented on Makefile
> +# Copyright (c) 2019-2024 Intel Corporation
Missing newline.

```suggestion
# Copyright (c) 2019-2024 Intel Corporation

```

2024-10-04 09:52 UTC, grom72 commented on Makefile
> +# Copyright (c) 2019-2024 Intel Corporation
Done

2024-10-04 10:09 UTC, janekmi approved these changes

2024-10-07 18:18 UTC, brianjmurrell requested changes
Pity that 8ea7616ce1eb548aab60ab9d3aa6f4928a90db27 was not based on 7e622f847c80d84b70608ea42c47b5d7abe8c8dd.  Please add a revert of 840acf8c98301dc6adfc55a837c3374f77412208 to this PR to revert that archiving notice.

2024-10-07 19:45 UTC, brianjmurrell approved these changes

2024-10-08 13:18 UTC, merged